#!/bin/sh
#
# $Id$

## Function to report failure
fail () {
  echo "!!! 00boot: $1 failed" >&2
  echo "!!! 00boot: consult the file 'README' for help" >&2
  exit 1
}

# Help message
helpmsg="Usage $0 [options]
Options: [defaults in brackets after description]"
helpmsg="$helpmsg
  --help                        print this message"
helpmsg="$helpmsg
  --with-aclocal=ACLOCAL        use aclocal program ACLOCAL [aclocal]"
helpmsg="$helpmsg
  --with-autoheader=AUTOHEADER  use autoheader program AUTOHEADER [autoheader]"
helpmsg="$helpmsg
  --with-automake=AUTOMAKE      use automake program AUTOMAKE [automake]"
helpmsg="$helpmsg
  --with-autoconf=AUTOCONF      use autoconf program AUTOCONF [autoconf]"
helpmsg="$helpmsg
  --include-deps                pass option --include-deps to automake [no]"

INCLUDEDEPS=""

## Process args
while test $# -gt 0 ; do
  option=$1
  case "$option" in
    -*=*) optarg=`echo "$option" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
  esac
  case $option in
    -h | -help | --help ) echo "$helpmsg"; exit 0;;
    -include-deps | --include-deps ) INCLUDEDEPS=" --include-deps";;
    -with-aclocal=* | --with-aclocal=* ) ACLOCAL="$optarg";;
    -with-autoheader=* | --with-autoheader=* ) AUTOHEADER="$optarg";;
    -with-automake=* | --with-automake=* ) AUTOMAKE="$optarg";;
    -with-autoconf=* | --with-autoconf=* ) AUTOCONF="$optarg";;
    *) echo "unrecognized option $option"; exit 1;;
  esac
  shift
done

echo "00boot: checking versions of aclocal, automake, autoheader and autoconf"


ACLOCAL=${ACLOCAL:-"aclocal"}
AUTOHEADER=${AUTOHEADER:-"autoheader"}
AUTOMAKE=${AUTOMAKE:-"automake"}
AUTOCONF=${AUTOCONF:-"autoconf"}

aclocal_version="`$ACLOCAL --version 2>/dev/null | sed -n '1s/^.* \([0-9.]*\)/\1/p'`"
autoheader_version="`$AUTOHEADER --version 2>/dev/null | sed -n '1s/^.* \([0-9.]*\)/\1/p'`"
automake_version="`$AUTOMAKE --version 2>/dev/null | sed -n '1s/^.* \([0-9.]*\)/\1/p'`"
autoconf_version="`$AUTOCONF --version 2>/dev/null | sed -n '1s/^.* \([0-9.]*\)/\1/p'`"
if test -z "$aclocal_version"; then
  fail "finding program aclocal"
fi
if test -z "$autoheader_version"; then
  fail "finding program autoheader"
fi
if test -z "$automake_version"; then
  fail "finding program automake"
fi
if test -z "$autoconf_version"; then
  fail "finding program autoconf"
fi

echo "00boot: using:"
printf "00boot:\t%-16s %s\n" "aclocal-$aclocal_version:" "`which $ACLOCAL`"
printf "00boot:\t%-16s %s\n" "autoheader-$autoheader_version:" "`which $AUTOHEADER`"
printf "00boot:\t%-16s %s\n" "automake-$automake_version:" "`which $AUTOMAKE`"
printf "00boot:\t%-16s %s\n" "autoconf-$autoconf_version:" "`which $AUTOCONF`"

## Generate the Makefile.in's and the configure script

echo "00boot: running aclocal"
$ACLOCAL -I misc || fail "aclocal"
echo "00boot: running autoheader"
$AUTOHEADER || fail "autoheader"
echo "00boot: running automake"
$AUTOMAKE $INCLUDEDEPS || fail "automake"
echo "00boot: running autoconf"
$AUTOCONF || fail "autoconf"

echo "00boot: success"
echo "
=================================================================

        00boot has been run.

        Now run './configure' with appropriate options
        to configure LALApps.

        See the LALApps README file for futher instructions

================================================================="
