#!/usr/bin/python
#
# $Id$

#
# =============================================================================
#
#                                   Preamble
#
# =============================================================================
#

"""
Excess power offline pipeline construction script.
"""

__author__ = "Kipp Cannon <kipp@gravity.phys.uwm.edu>"
__date__ = "$Date$"[5:-2]
__version__ = "$Revision$"[11:-2]

from optparse import OptionParser

from glue import pipeline
import power


#
# =============================================================================
#
#                                 Command Line
#
# =============================================================================
#

