#!/usr/bin/python
#
# $Id$
#
# Copyright (C) 2006  Kipp C. Cannon
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


#
# =============================================================================
#
#                                   Preamble
#
# =============================================================================
#


"""
Program for changing the instrument names appearing in the tables in a LIGO
Light Weight XML file.  Used as a hack to allow the standard burst
coincidence tools in pylal when looking for coincidences between
a single instrument's science and auxiliary channels.
"""


from optparse import OptionParser
import sys

from glue.ligolw import table
from glue.ligolw import lsctables
from pylal import llwapp


__author__ = "Kipp Cannon <kipp@gravity.phys.uwm.edu>"
__version__ = "$Revision$"[11:-2]
__date__ = "$Date$"[7:-2]


#
# =============================================================================
#
#                                 Command Line
#
# =============================================================================
#


def parse_command_line():
	parser = OptionParser(version="%prog CVS $Id$")
	parser.add_option("-m", "--map", metavar = "old,new", action = "append", default = [], help = "relabel instrument \"old\" to \"new\"")
	parser.add_option("-p", "--program", metavar = "name", default = "power", help = "set name of program whose triggers are being modified (default = \"power\")")
	parser.add_option("-v", "--verbose", action = "store_true", help = "be verbose")
	options, filenames = parser.parse_args()

	try:
		map = {}
		for m in options.map:
			old, new = m.split(",")
			map[old] = new
	except Exception, e:
		raise ValueError, "unable to parse mappings: %s" % str(e)
	options.map = map

	return options, (filenames or [None])


#
# =============================================================================
#
#                                  Remapping
#
# =============================================================================
#


def remap_instruments(doc, program_name, mapping, verbose = False):
	if verbose:
		print >>sys.stderr, "remapping instruments ..."

	#
	# process table
	#

	ids = llwapp.get_process_ids_by_program(doc, program_name)
	for row in table.get_table(doc, lsctables.ProcessTable.tableName):
		if llwapp.bisect_contains(ids, row.process_id):
			try:
				row.ifos = mapping[row.ifos]
			except KeyError:
				pass

	#
	# search_summary table
	#

	for row in table.get_table(doc, lsctables.SearchSummaryTable.tableName):
		if llwapp.bisect_contains(ids, row.process_id):
			try:
				row.ifos = mapping[row.ifos]
			except KeyError:
				pass

	#
	# sngl_burst table
	#

	for row in table.get_table(doc, lsctables.SnglBurstTable.tableName):
		try:
			row.ifo = mapping[row.ifo]
		except KeyError:
			pass

	#
	# done
	#

	return doc


#
# =============================================================================
#
#                                     Main
#
# =============================================================================
#


options, filenames = parse_command_line()


for filename in filenames:
	doc = llwapp.load_filename(filename, options.verbose)
	remap_instruments(doc, options.program, options.mapping, verbose = options.verbose)
	llwapp.write_filename(doc, filename, options.verbose)
