#!/bin/bash

for filename in "${@}" ; do
	echo ${filename}
	tmp=$(mktemp)
	ligolw_cut --delete-table time_slide --delete-table coinc_event --delete-table coinc_event_map --delete-table coinc_definer <${filename} | sed -e "/ligolw_burca/d" -e "/ligolw_binjfind/d" -e "/ligolw_tisi/d" >${tmp} && mv -f ${tmp} ${filename}
done
