LATEX := pdflatex
DOCUMENT := power
GRAPHIC_FILES := figures/pipeline.pdf
GRAPHIC_FILES += figures/sk_histogram.png
GRAPHIC_FILES += figures/sksk.png
GRAPHIC_FILES += figures/freqdomainfilter.pdf
GRAPHIC_FILES += figures/timedomainfilter_04hz.pdf
GRAPHIC_FILES += figures/timedomainfilter_16hz.pdf
GRAPHIC_FILES += figures/Z_histogram.png
GRAPHIC_FILES += figures/tiles_histogram.png
GRAPHIC_FILES += figures/tiles_histogram_adjusted.png
GRAPHIC_FILES += figures/h_histogram.png
GRAPHIC_FILES += figures/plotbinj_L1_4.png
GRAPHIC_FILES += figures/plotbinj_L1_5.png
GRAPHIC_FILES += figures/clustering_example.png
GRAPHIC_FILES += figures/plotburca2-P-793154128-2525061.png
GRAPHIC_FILES += figures/btlwnb_example_+.pdf
GRAPHIC_FILES += figures/btlwnb_example_x.pdf
BIB_FILES := refs.bib

include LaTeX.Rules
