repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace

      - id: end-of-file-fixer

      - id: check-yaml
        files: ^\.pre-commit-config.yaml$

      - id: check-yaml
        args: [--unsafe]
        files: ^\.gitlab.*\.yml$

      - id: file-contents-sorter
        args: [--unique]
        files: \.gitattributes$

      - id: check-executables-have-shebangs

  - repo: https://git.ligo.org/lscsoft/lalsuite-code-quality.git
    rev: v0.5
    hooks:
      - id: remove-executable-bits
        exclude: 00boot$|common/|conda/|debian/|gnuscripts/

      - id: fix-makefile-indents

      - id: fix-gitignore-entries

      - id: fix-mailmap-authors

      - id: make-code-pretty
