#!/bin/sh

## Function to report failure
fail () {
  echo "!!! 00boot: $1 failed" >&2
  echo "!!! 00boot: consult the file 'README' for help" >&2
  exit 1
}

echo "00boot: running autoreconf"
LIBTOOLIZE=true autoreconf || fail "autoreconf"

echo "00boot: success"
echo "
=================================================================

        00boot has been run.

        Now run './configure' with appropriate options
        to configure LALSuite.

================================================================="
