name: lalsuite-dev
channels:
  - conda-forge
dependencies:
  - astropy >=1.1.1
  - autoconf
  - automake
  - bc
  - cfitsio
  - doxygen
  - fftw
  - freezegun
  - c-compiler
  - gsl
  - gwpy
  - h5py
  - hdf5
  - healpy >=1.17.3
  - help2man >=1.37
  - igwn-ligolw >=2.1.0
  - igwn-segments
  - ldas-tools-framecpp <3.0.0a0
  - libframel <9.0.0a0
  - ligo-gracedb
  - lscsoft-glue >=2.0.0
  - make
  - matplotlib-base
  - metaio
  - mpmath >=1.0.0
  - numpy
  - openmpi
  - pillow
  - pip
  - pkg-config >=0.18.0
  - pre-commit
  - pytest
  - python <3.14.0a0
  - scipy >=0.9.0
  - swig >=3.0.10
  - sympy
  - tqdm
  - xz
  - zlib
