#!/usr/bin/env bash

USAGE="lalinference_mpi_wrapper --mpirun MPIRUN --executable EXECUTABLE --np NCPUS [arg1] [arg2] ... \\
          Runs MPIRUN --np NCPUS EXECUTABLE [arg1] [arg2] ... \\
"

MCMCARGS=""

while [[ $# -ge 1 ]]
do
        key=$1

        case $key in
                --np)
                        NP="$2"
                        shift 2
                        ;;
                --executable)
                        EXE="$2"
                        shift 2
                        ;;
                --mpirun)
                        MPIRUN="$2"
                        shift 2
                        ;;
                *)
                        MCMCARGS="$MCMCARGS $1"
                        shift
                        ;;

        esac
done

echo "$MPIRUN -np $NP $EXE $MCMCARGS"
$MPIRUN -np $NP $EXE $MCMCARGS
