#!/usr/bin/env python3

"""Interact with a GitLab server through its API."""

__author__ = "Karl Wette"
__copyright__ = "Copyright (C) 2025 Karl Wette"

import argparse
import logging
import os
import sys
import time
from io import BytesIO
from pathlib import Path
from textwrap import dedent
from urllib.parse import urlparse
from zipfile import ZipFile

import gitlab
from natsort import natsorted

# configure logging
LOGGER = logging.getLogger(__name__.rsplit(".", 1)[-1])
try:
    from coloredlogs import ColoredFormatter as _Formatter
except ImportError:
    _Formatter = logging.Formatter
if not LOGGER.hasHandlers():
    _LOG_HANDLER = logging.StreamHandler()
    _LOG_HANDLER.setFormatter(
        _Formatter(
            fmt="[%(asctime)s] %(levelname)+8s: %(message)s",
        )
    )
    LOGGER.addHandler(_LOG_HANDLER)
LOGGER.setLevel(logging.DEBUG)


def parse_command_line():
    """Parse command line"""

    # Create parser
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--token-env-var",
        type=str,
        default=None,
        help="Environment variable containing GitLab access token, if required",
    )
    parser.add_argument(
        "server",
        type=str,
        help="GitLab server",
    )
    parser.add_argument(
        "repo",
        type=str,
        help="GitLab repository",
    )
    subparsers = parser.add_subparsers(dest="command", help="subcommand help")
    subparsers.required = True

    # Subparser for get-artifacts command
    parser_get_artifacts = subparsers.add_parser(
        "get-artifacts", help="get-artifacts help"
    )
    parser_get_artifacts.set_defaults(subcommand=get_artifacts)
    parser_get_artifacts.add_argument(
        "ref_name", type=str, help="Get artifacts for this reference name"
    )
    parser_get_artifacts.add_argument(
        "--latest-tag",
        action="store_true",
        help="Interpret `ref_name` as a tag prefix, and get artfacts for the most recent tag with a successful build",
    )
    parser_get_artifacts.add_argument(
        "--write-ref-name",
        type=Path,
        help="Write the reference name artifacts are being downloaded for to this file",
    )
    parser_get_artifacts.add_argument(
        "job_name", type=str, help="Get artifacts from this job name"
    )

    # Subparser for doxygen-index command
    parser_doxygen_index = subparsers.add_parser(
        "doxygen-index", help="doxygen-index help"
    )
    parser_doxygen_index.set_defaults(subcommand=doxygen_index)

    # Parse command line
    args = parser.parse_args()

    return args


def write_artifact_download_progress(log_message, artifacts_archive):
    """Write progress messages when downloading artifacts"""
    n = 0
    t0 = time.perf_counter()

    def write(b):
        nonlocal n
        nonlocal t0
        n += len(b)
        t = time.perf_counter()
        if t - t0 > 10:
            n_MB = 1e-6 * n
            LOGGER.info(f"{log_message}: wrote {n_MB:0.1f} MB")
            t0 = t
        artifacts_archive.write(b)

    return write


def get_artifacts(server, repo, args):
    """Retrieve artifacts from GitLab project reference and job"""

    # if requested, find latest tag with given prefix
    if args.latest_tag:
        tags = repo.tags.list(iterator=True)
        matching_tags = [t.name for t in tags if t.name.startswith(args.ref_name)]
        for tag in reversed(natsorted(matching_tags)):
            head_pipeline = repo.pipelines.latest(ref=tag)
            LOGGER.info(f"pipeline status for tag {tag}: {head_pipeline.status}")
            if head_pipeline.status == "success":
                ref_name = tag
                if args.write_ref_name:
                    args.write_ref_name.write_text(ref_name + "\n")
                break
        else:
            LOGGER.critical(
                f"could not find a tag matching '{args.latest_tag}' with a successful pipeline"
            )
            sys.exit(1)
    else:
        ref_name = args.ref_name

    # download latest artifacts as ZIP archive
    log_message = (
        f"downloading latest artifacts for ref={ref_name}, job={args.job_name}"
    )
    LOGGER.info(f"{log_message}: started")
    artifacts_archive = BytesIO()
    repo.artifacts.download(
        ref_name,
        args.job_name,
        streamed=True,
        action=write_artifact_download_progress(log_message, artifacts_archive),
    )
    LOGGER.info(f"{log_message}: done")

    # extract artifacts from ZIP file
    with ZipFile(artifacts_archive) as zf:
        zf.extractall()


def doxygen_index(server, repo, args):
    """Generate a top-level index for Doxygen documentation"""

    # get Doxygen pages from list of GitLab environments
    environments = repo.environments.list(all=True)
    path_prefixes = []
    for env in environments:
        if env.state == "available" and env.name.startswith("pages/doc/lalsuite-v"):
            url = urlparse(env.external_url)
            path_prefixes.append(Path(url.path).name)
    path_prefixes = natsorted(path_prefixes)
    LOGGER.info(
        "found Doxygen documentation for releases: %s",
        ", ".join(path_prefixes) if path_prefixes else "none",
    )

    # generate index entries
    entry_template = "<li><a href='{}/index.html'>{}</a></li>"
    entries = [entry_template.format("dev", "development version")]
    for p in reversed(path_prefixes):
        entries.append(entry_template.format(p, "release version " + p))

    # generate index
    index = dedent("""
        <!DOCTYPE html>
        <html>
        <head>
        <title>LALSuite Documentation</title>
        </head>
        <body>
        <h1>LALSuite Documentation</h1>
        Please select documentation for:
        <ul>
        {}
        </ul>
        </body>
        </html>
        """).format("\n".join(entries))

    # write index
    Path("index.html").write_text(index.strip() + "\n")
    LOGGER.info("wrote index.html")


def main():
    """Main program"""

    # parse command line
    args = parse_command_line()

    # interface to GitLab repository
    if args.token_env_var:
        server = gitlab.Gitlab(
            args.server, private_token=os.environ[args.token_env_var]
        )
        server.auth()
    else:
        server = gitlab.Gitlab(args.server)
    repo = server.projects.get(args.repo)
    LOGGER.info(f"authenticated to {args.server}/{args.repo}")

    # execute subcommand
    args.subcommand(server, repo, args)

    return 0


if __name__ == "__main__":
    sys.exit(main())
