.TH LALAPPS_FRINFO 1 "11 July 2001" LALApps LALApps
.SH NAME
lalapps_frinfo - prints information about a frame file

.SH SYNOPSIS
.B lalapps_frinfo
.IR framefiles

.SH DESCRIPTION
.PP
\fIlalapps_frinfo\fP prints information about the frame files including the
frame header information and a summary of all ADC channels in the frame.

.SH AUTHOR
Jolien Creighton
