/*----------------------------------------------------------------------- 
 * 
 * File Name: FindChirpView.c
 *
 * Author: Brady, P. R., and Brown, D. A.
 * 
 * Revision: $Id$
 * 
 *-----------------------------------------------------------------------
 */

#if 0
<lalVerbatim file="FindChirpViewCV">
Author: Brown D. A.
$Id$
</lalVerbatim>

<lalLaTeX>
\subsection{Module \texttt{FindChirpView.c}}
\label{ss:FindChirpView.c}

Functions for viewing metadata from the LIGO database generated by findchirp
in the \verb|sngl_inspiral| event table.

\vfill{\footnotesize\input{FindChirpViewCV}}
</lalLaTeX>
#endif

#include <math.h>
#include <lal/LALStdlib.h>
#include <lal/LALConstants.h>
#include <lal/AVFactories.h>
#include <lal/LALXMGRInterface.h>
#include <lal/FindChirp.h>
#include <lal/FindChirpView.h>

NRCSID (FINDCHIRPVIEWC, "$Id$");

#if 0

/* ---------------------------------------------------------------------- */
LALFindChirpInspiralTimingGraph (
    LALStatus          *status,
    InspiralLDASJob    *jobHead,
    const CHAR         *fileName
    )
{
  CHARVector           *timingTitle = NULL;
  FILE                 *timingFP    = NULL;
  LIGOTimeGPS          *stopGPS     = NULL;
  InspiralLDASJob      *currentJob  = NULL;
  InspiralLDASJob      *jobTail     = NULL;
  UINT4                 numJobs     = 1;

  INITSTATUS( status, "LALFindChirpInspiralTimingGraph", FINDCHIRPVIEWC );
  ATTATCHSTATUSPTR( status );

  ASSERT( jobHead, status, FINDCHIRPVIEWH_ENULL, FINDCHIRPVIEWH_MSGENULL );
  ASSERT( fileName, status, FINDCHIRPVIEWH_ENULL, FINDCHIRPVIEWH_MSGENULL );


  /* create a vector for the graph title */
  LALCHARCreateVector( status->statusPtr, &timingTitle, (UINT4) 128 );
  CHECKSTATUSPTR( status );

  /* find the last job in the list */
  for ( currentJob = jobHead; currentJob->next; currentJob = currentJob->next )
  {
    numJobs++;
  }
  jobTail = currentJob;

  /* create the title and open the graph */
  LALFindChirpXMGRTitle( status->statusPtr, timingTitle, 
      &(jobHead->startGPS), &(jobHead->stopGPS), "Inspiral Timing" );
  CHECKSTATUSPTR( status );

  LALFindChirpXMGROpenFile ( status->statusPtr, &timingFP, 
      timingTitle->data, fileName );
  CHECKSTATUSPTR( status );

  /* print the header for the timing graph */

  /* print the timing data to the file */
  for ( currentJob = jobHead; currentJob; currentJob = currentJob->next )
  {
    fprintf( timingFP, "%d\t%f\t%f\n", 
        currentJob->numEvents, currentJob->mpiTime, currentJob->totalTime );
  }

  /* print the header for the timing graph */

  /* destroy the vector for the graph title */
  LALCHARDestroyVector( status->statusPtr, &timingTitle );
  CHECKSTATUSPTR( status );

  DETATCHSTATUSPTR( status );
  RETURN( status );
}

#endif
