#!/usr/bin/env perl
# Author: Karl Wette, 2022

use strict;

my $subdir = shift @ARGV;

my %authors;

open IN, "$subdir/.AUTHORS" or die $!;
binmode IN, ":encoding(UTF-8)";
while (<IN>) {
  chomp;
  next if /^\s*#/;

  $authors{$_} = "historical";

}

open IN, "git log --full-history HEAD -- $subdir/ | git shortlog --summary |" or die $!;
binmode IN, ":encoding(UTF-8)";
while (<IN>) {
  chomp;

  my ($n, $author) = m/^\s*(\d+)\s+(.+)$/ or die;

  $authors{$author} = "git history";

}

open OUT, ">$subdir/.AUTHORS" or die $!;
binmode OUT, ":encoding(UTF-8)";
print OUT <<EOF;
# This file contains historical authors collected from the pre-Git version
# history, copyright notices, documentation, and other sources. It should
# not be modified; all authors should now be deduced from the Git history.
EOF
foreach my $author (sort { $a cmp $b } keys(%authors)) {
  print OUT "$author\n" if $authors{$author} eq "historical";
}

open OUT, ">$subdir/AUTHORS" or die $!;
binmode OUT, ":encoding(UTF-8)";
foreach my $author (sort { $a cmp $b } keys(%authors)) {
  print OUT "$author\n";
}
