#!/usr/bin/env perl
# Author: Karl Wette, 2022

use strict;

my $subdir = shift @ARGV;

my %authors;

open IN, "$subdir/.historical_authors" or die $!;
binmode IN, ":encoding(UTF-8)";
while (<IN>) {
  chomp;
  next if /^\s*#/;

  $authors{$_} = "historical";

}

open IN, "git log --full-history --no-merges HEAD -- $subdir/ | git shortlog --summary |" or die $!;
binmode IN, ":encoding(UTF-8)";
while (<IN>) {
  chomp;

  my ($n, $author) = m/^\s*(\d+)\s+(.+)$/ or die;

  $authors{$author} = "git history";

}

if (defined($ENV{"UPDATE_AUTHORS_WITH_GIT_BLAME"})) {

  my @files;
  open IN, "git ls-files -- $subdir/ |" or die $!;
  binmode IN, ":encoding(UTF-8)";
  while (<IN>) {
    chomp;
    push @files, $_;
  }
  my $nfiles = @files;
  for (my $i = 0; $i < @files; ++$i) {
    print STDERR "$0: updating authors of $subdir: file $i of $nfiles: $files[$i]\n";
    open IN2, "git blame --line-porcelain -- $files[$i] |" or die $!;
    binmode IN2, ":encoding(UTF-8)";
    while (<IN2>) {
      chomp;
      next unless s/^author //;
      next if defined($authors{$_});
      $authors{$_} = "git blame";
    }
  }

  open OUT, ">$subdir/.historical_authors" or die $!;
  binmode OUT, ":encoding(UTF-8)";
  print OUT <<EOF;
# This file contains historical authors collected from the pre-Git version
# history, copyright notices, documentation, git blame, and other sources.
# It should not be modified except by the 'update_authors' script.
EOF
  foreach my $author (sort { $a cmp $b } keys(%authors)) {
    print OUT "$author\n" if $authors{$author} ne "git history";
  }

}

open OUT, ">$subdir/AUTHORS" or die $!;
binmode OUT, ":encoding(UTF-8)";
foreach my $author (sort { $a cmp $b } keys(%authors)) {
  print OUT "$author\n";
}
