#!/usr/bin/python
"""
  lalapps_pulsar_parameter_estimation -- pipeline for creating Condor DAG to
                                         perform pulsar parameter estimation
                                         for the time domain analysis
  
  This has been greatly inspired (well blatently hacked together from) the stochastic pipeline by
  Adam Mercer and the frequency domain binary pulsar search by Chris Messenger.
  
  Matt Pitkin 07/03/08
  
  $Id$
"""

__author__ = 'Matt Pitkin <matthew@astro.gla.ac.uk>'
__date__ = '$Date$'
__version__ = '$Revision$'

# import required modules
import sys
import os
import getopt
import re
import string
import tempfile
import ConfigParser
import exceptions

# append the lalapps python path
sys.path.append('/home/matthew/lscsoft/lib/python')

# import the lalapps pipeline modules
from glue import pipeline
import pulsar_parameter_estimation

# program usage
def usage():
  msg = """\
Usage: lalapps_pulsar_parameter_estimation_pipe [options]

  -h, --help               display this message
  -v, --version            print version information and exit
  -V, --verbose            run lalapps_heterodyne_pulsar in verbose mode  
  -F, --config-file FILE   use configuration file FILE
  -l, --log-path PATH      directory to write condor log file
  -u, --ul                 output the upper limit
  -m, --mcmc               perform search as an MCMC
  -c, --covariance         use covariance file if available
  """
  print >> sys.stderr, msg
  
# parse the command line options to figure out what we should do
shortop = "hvF:l:Vumc"
longop = [
  "help",
  "version",
  "config-file=",
  "log-path=",
  "verbose",
  "ul",
  "mcmc",
  "covariance",
  ]

try:
  opts, args = getopt.getopt(sys.argv[1:], shortop, longop)
except getopt.GetoptError:
  usage()
  sys.exit(1)
  
# default options
config_file = None
log_path = None
do_verbose = None
do_ul = None
do_mcmc = None
do_cov = None
do_only = None

# process options
for o, a in opts:
  if o in ("-v", "--version"):
    print "lalapps_pulsar_parameter_estimation_pipe version", __version__
    sys.exit(0)
  elif o in ("-h", "--help"):
    usage()
    sys.exit(0)
  elif o in ("-F", "--config-file"):
    config_file = a
  elif o in ("-l", "--log-path"):
    log_path = a
  elif o in ("-V", "--verbose"):
    do_verbose = 1 # this is the set verbose when running lalapps_heterodyne_pulsar NOT this script
  elif o in ("-u", "--ul"):
    do_ul = 1 # output the upper limit
  elif o in ("-m", "--mcmc"):
    do_mcmc = 1 # perform mcmc
  elif o in ("-c", "--covariance"): 
    do_cov = 1 # see if there is a covariance matrix
  elif o in ("-o", "--only-joint"):
    do_only = 1; # only perform the joint posterior for MCMC
  else:
    print >> sys.stderr, "Unknown option:", o
    usage()
    sys.exit(1)

# test arguments for validity
if not config_file:
  print >> sys.stderr, "No configuration file specified."
  print >> sys.stderr, "Use --config-file FILE to specify location."
  sys.exit(1)

if not log_path:
  print >> sys.stderr, "No log file path specified."
  print >> sys.stderr, "Use --log-path PATH to specify a location."
  sys.exit(1)

# try and make a directory to store the cache files and job logs
try: os.mkdir('logs')
except: pass

# create the config parser object and read in the ini file
cp = ConfigParser.ConfigParser()
cp.read(config_file)

# create a log file that the Condor jobs will write to
basename = re.sub(r'\.ini',r'',config_file) # remove .ini from config_file name

logfile = log_path + '/' + basename + '.dag.log'

fh = open(logfile, "w" ) # creates file
fh.close()

# create the DAG writing the log to the specified directory
dag = pipeline.CondorDAG(logfile)
dag.set_dag_file(basename)

# create Condor Jobds that will be used in the dag
parameter_job = pulsar_parameter_estimation.parameterJob(cp)

# set Condor .sub submit file names
subsuffix = '.sub'
df_job.set_sub_file(basename + '.datafind' + subsuffix)
coarse_job.set_sub_file(basename + subsuffix)
fine_job.set_sub_file(basename +  subsuffix)
update_job.set_sub_file(basename + subsuffix)

# set values from config file
pulsar_param_dir = cp.get('data','pulsar_param_dir')
input_dir = cp.get('data','input_dir')

# actual info on the analysis
detectors = cp.get('input','detectors')
minh0 = cp.get('input','minh0')
maxh0 = cp.get('input','maxh0')
h0steps = cp.get('input','h0steps')
phi0steps = cp.get('input','phi0steps')
psisteps = cp.get('input','psisteps')
cisteps = cp.get('input','cisteps')

if do_ul:
  dob_ul = cp.get('input','dob_ul')

output_dir = cp.get('output','output_path')

# get the list of pulsar parameter files
param_files = os.listdir(pulsar_param_dir)
param_files.sort() # sort the files into alphabetical order

# check what the MCMC parameters are
if do_mcmc:
  iterations = cp.get('mcmc','iterations') # number of MCMC iterations
  burnin = cp.get('mcmc','burn_in') # number of burn iterations for MCMC
  temperature = cp.get('mcmc','temperature') # temperature of burn in  
  outputrate = cp.get('mcmc','output_rate') # output rate of MCMC chain

  if do_cov:
    covdir = cp.get('mcmc','cov_dir') # directory containing cov matrices  
    earth = cp.get('mcmc','earth_ephem') # Earth ephemeris
    sun = cp.get('mcmc','sun_ephem') # Sun ephemeris

    cov_files = os.listdir(covdir)
    cov_files.sort()

# get the list of fine heterodyned data files
input_files = os.listdir(input_dir)
input_files.sort()

pulsars = [] # create list for parameter estimation nodes
  
i = 0
j = 0
while i < len(param_files):
  if ".par" in param_files[i]:
    pulsar = 'J' + re.sub(r'\.par',r'',param_files[i]) # set pulsar name from
    param_file = pulsar_param_dir + '/' + param_files[i]
      
    # find correct input file
    k=0
    while k < len(input_files):
      if pulsar in input_files[k]:
        data_file = input_dir + '/' + input_files[k]
        break

      data_file = None
      k = k+1

      # if no file is set then tell me and move onto next pulsar
      if data_file == None:
        print >> sys.stderr, "No file set for PSR %s" % (pulsar)
        i = i+1
        continue 
      
      # add parameterNode for DAG
      pulsars.append(pulsar_parameter_estimation.parameterNode(parameter_job))

      pulsars[j].set_detectors(detectors)
      pulsars[j].set_param_file(param_file)
      pulsars[j].set_pulsar(pulsar)
      pulsars[j].set_input_dir(input_dir)
      pulsars[j].set_output_dir(output_dir)
      pulsars[j].set_maxh0(maxh0)
      pulsars[j].set_minh0(minh0)
      pulsars[j].set_h0steps(h0steps)
      pulsars[j].set_phi0steps(phi0steps)
      pulsars[j].set_cisteps(cisteps)
      pulsars[j].set_psisteps(psisteps)
     
      if do_ul:
        pulsars[j].set_ul()
       
      if do_verbose:
        pulsars[j].set_verbose()
      
      if do_mcmc:
        pulsars[j].set_mcmc()
        pulsars[j].set_interations(iterations)
        pulsars[j].set_burnin(burnin)
        pulsars[j].set_temperature(temperature)
        pulsars[j].set_outputrate(outputrate)

        # if there is a covariance matrix set this
        m=0        
        if do_cov:
          while m < len(cov_files):
            if ".mat" in cov_files[m]:
              p = 'J' + re.sub(r'\.mat',r'',cov_files[m])
              
              if pulsar == p:
                cov_file = covdir + '/' + cov_files[m]                
                break;

          pulsars[j].set_covfile(cov_file)
          pulsars[j].set_earth(earth_ephem)
          pulsars[j].set_sun(sun_ephem)

          if do_only:
            pulsars[j].set_onlyjoint()

      dag.add_node(pulsars[j])
      j = j+1
      
    i = i+1

# write out DAG
dag.write_sub_files()
dag.write_dag()

sys.exit(0)
