.TH LALAPPS_INSPINJ 1 "7 May 2002" LALApps LALApps
.SH NAME
lalapps_inspinj - produces inspiral injection ILWD and LIGOLw files

.SH SYNOPSIS
.B lalapps_inspinj
.RB [ \-\-help ]
.RB \-\-seed
.IR seed
.RB \-\-gps\-start\-time
.IR tstart
.RB \-\-gps\-end\-time 
.IR tend
.RB \-\-time\-step
.IR tstep
.RB [ \-\-datafile
.IR file ] 

.SH DESCRIPTION
.PP
\fIlalapps_inspinj\fP generates a number of inspiral parameters suitable
for using in a Monte Carlo injection to test the efficiency of a inspiral
search.  The various parameters (detailed below) are randomly chosen and
are appropriate for a particular population of binary neutron stars whose
spatial distribution includes the Milky Way and a number of extragalactic
objects that are input in a datafile.  The possible mass pairs for the
binary neutron star companions are also specified in a (different) datafile.

The output of this program is a list of the injected events, starting at
the specified start time, ending at the specified end time, and containing
one set of random inspiral parameters every specified time step.  The output
is written to a file called injections\-X.xml, where X is the value of the
random number seed chosen, which is a LIGOLw format file.  In addition, an
ascii log file called injlog.txt.

\fIlalapps_inspinj\fP also produces two ILWD-format files,
injepochs.ilwd and injparams.ilwd, that contain, respectively, the GPS times
suitable for inspiral injections, and the intrinsic inspiral signal parameters
to be used for those injections.

The file injepochs.ilwd contains a sequence of integer pairs representing the
injection GPS time in seconds and residual nano-seconds.  The file
injparams.ilwd contains the intrinsic binary parameters for each injection,
which is a sequence of eight real numbers representing (in order) (1) the total
mass of the binary system (in solar masses), (2) the dimensionless reduced mass
-- reduced mass per unit total mass -- in the range from 0 (extreme mass ratio)
to 0.25 (equal masses), (3) the distance to the system in meters, (4) the
inclination of the binary system orbit to the plane of the sky in radians, (5)
the colaescence phase in radians, (6) the longitude to the direction of the
source in radians, (7) the latitude to the direction of the source in radians,
(8) and the polarization angle of the source in radians.

.SH OPTIONS
.TP
\fB\-\-help\fR, \fB\-h\fR
Print a help message.
.TP
\fB\-\-seed\fR=\fIseed\fR, \fB\-s\fR \fIseed\fR
Sets the random number generator seed.
.TP
\fB\-\-gps\-start\-time\fR=\fItstart\fR, \fB\-a\fR \fItstart\fR
Sets the start time in GPS seconds.
.TP
\fB\-\-gps\-stop\-time\fR=\fItstop\fR, \fB\-b\fR \fItstop\fR
Sets the stop time in GPS seconds.
.TP
\fB\-\-time\-step\fR=\fItstep\fR, \fB\-t\fR \fItstep\fR
Sets the time step interval in seconds.
.TP
\fB\-\-datafile\fR=\fIfile\fR, \fB\-f\fR \fIfile\fR
Specifies the source datafile listing the various sources in the population.
(Default is inspsrcs.dat).

.SH ENVIRONMENT
.TP
.BR LALAPPS_DATA_PATH
Directory to look for required data file BNSMasses.dat and the default
data file inspsrcs.dat.

.SH AUTHOR
Jolien Creighton, Patrick Brady
