#!/usr/bin/python
#
# $Id$
#
# Copyright (C) 2009  Kipp Cannon
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


#
# =============================================================================
#
#                                   Preamble
#
# =============================================================================
#


import bisect
import numpy
from new import instancemethod
from optparse import OptionParser
try:
	import sqlite3
except ImportError:
	# pre 2.5.x
	from pysqlite2 import dbapi2 as sqlite3
import sys


from glue import segments
from glue.ligolw import lsctables
from glue.ligolw import dbtables
from glue.ligolw import utils
from pylal import rate
from pylal import db_thinca_rings
from pylal import git_version
from pylal.xlal.datatypes.ligotimegps import LIGOTimeGPS
from glue.ligolw import table
from pylal import llwapp

lsctables.LIGOTimeGPS = LIGOTimeGPS


__author__ = "Kipp Cannon <kcannon@ligo.org>"
__version__ = "git id %s" % git_version.id
__date__ = git_version.date

#
# =============================================================================
#
#                                 Command Line
#
# =============================================================================
#


def parse_command_line():
	parser = OptionParser(
		version = "Name: %%prog\n%s" % git_version.verbose_msg,
		usage = "%prog [options] [file ...]",
		description = "%prog does blah blah blah."
	)
	parser.add_option("-p", "--live-time-program", metavar = "name", help = "Set the name of the program whose entries in the search_summary table will set the search live time.  Required.")
	parser.add_option("--veto-segments-name", help = "Set the name of the segments to extract from the segment tables and use as the veto list.")
#	parser.add_option("--categories", metavar = "{\"mchirp-ifos-oninstruments\",\"mtotal-ifos-oninstruments\",\"oninstruments\"}", help = "Select the event categorization algorithm.  Required.")
#	parser.add_option("-b", "--mass-bins", metavar = "mass,mass[,mass,...]", help = "Set the boundaries of the mass bins in solar masses.  The lowest and highest bounds must be explicitly listed.  Example \"0,5,inf\".  Required if mass-based categorization algorithm has been selected.")
	parser.add_option("--categories", metavar = "{\"frequency-ifos-oninstruments\",\"oninstruments\"}", help = "Select the event categorization algorithm.  Required.")
	parser.add_option("-b", "--frequency-bins", metavar = "frequency,frequency[,frequency,...]", help = "Set the boundaries of the frequency bins in Hz.  The lowest and highest bounds must be explicitly listed.  Example \"0,5,inf\".  Required if frequency-based categorization algorithm has been selected.")
	parser.add_option("--rank-by", metavar = "{\"snr\",\"uncombined-ifar\",\"likelihood\"}", help = "Select the event ranking method.  Required.")
	parser.add_option("-t", "--tmp-space", metavar = "path", help = "Path to a directory suitable for use as a work area while manipulating the database file.  The database file will be worked on in this directory, and then moved to the final location when complete.  This option is intended to improve performance when running in a networked environment, where there might be a local disk with higher bandwidth than is available to the filesystem on which the final output will reside.")
	parser.add_option("-n","--extrapolation-num",action="store",type="int",default=0, metavar="num",help="number of time-slide points to use in FAR extrapolation" )
	parser.add_option("-v", "--verbose", action = "store_true", help = "Be verbose.")
	options, filenames = parser.parse_args()

	#
	# categories and ranking
	#

#	if options.categories not in ("mchirp-ifos-oninstruments", "mtotal-ifos-oninstruments", "oninstruments"):
#		raise ValueError, "missing or unrecognized --categories option"
        if options.categories not in ("frequency-ifos-oninstruments", "oninstruments"):
                raise ValueError, "missing or unrecognized --categories option"
        if options.rank_by not in ("snr", "uncombined-ifar", "likelihood"):
                raise ValueError, "missing or unrecognized --rank-by option"

#	if options.categories in ("mchirp-ifos-oninstruments", "mtotal-ifos-oninstruments"):
#		if options.rank_by != "snr":
#			raise ValueError, "--rank-by must be \"snr\" if --categories is \"%s\"" % options.categories
#		options.populate_column = "false_alarm_rate"
#	else:
#		if options.rank_by == "snr":
#			raise ValueError, "--rank-by must be \"uncombined-ifar\" or \"likelihood\" if --categories is \"%s\"" % options.categories
#		options.populate_column = "combined_far"

        if options.categories in ("frequency-ifos-oninstruments"):
                if options.rank_by != "snr":
                        raise ValueError, "--rank-by must be \"snr\" if --categories is \"%s\"" % options.categories
                options.populate_column = "false_alarm_rate"
        else:
                if options.rank_by == "snr":
                        raise ValueError, "--rank-by must be \"uncombined-ifar\" or \"likelihood\" if --categories is \"%s\"" % options.categories
                options.populate_column = "combined_far"

	#
	# parse mass bins
	#

#	if options.categories in ("mchirp-ifos-oninstruments", "mtotal-ifos-oninstruments"):
#		if options.mass_bins is None:
#			raise ValueError, "--mass-bins required with category algorithm \"%s\"" % options.categories
#		options.mass_bins = sorted(map(float, options.mass_bins.split(",")))
#		if len(options.mass_bins) < 2:
#			raise ValueError, "must set at least two mass bin boundaries (i.e., define at least one mass bin)"
#		options.mass_bins = rate.IrregularBins(options.mass_bins)
        if options.categories in ("frequency-ifos-oninstruments"):
                if options.frequency_bins is None:
                        raise ValueError, "--frequency-bins required with category algorithm \"%s\"" % options.categories
                options.frequency_bins = sorted(map(float, options.frequency_bins.split(",")))
                if len(options.frequency_bins) < 2:
                        raise ValueError, "must set at least two frequency bin boundaries (i.e., define at least one frequency bin)"
                options.frequency_bins = rate.IrregularBins(options.frequency_bins)

	#
	# other
	#

	if options.live_time_program is None:
		raise ValueError, "missing required option -p or --live-time-program"

	#
	# done
	#

	return options, (filenames or [None])


#
# =============================================================================
#
#                               Helper Functions
#
# =============================================================================
#


def extrapolation_coeffs(rank_by, N, reputations, t):
	#
	# calculate the FAR extrapolation coefficients
	#

	#
	# get just the loudest N in reputations
	#

	if len(reputations) < 2:
		print >>sys.stderr,"Warning: found a category with less than 2 background triggers, cannot perform extrapolation for this category"
		return (0, (0, 0))

	x = reputations[-N:]

	if rank_by == "snr":
		y = range(1, len(x) + 1, 1)
		y.reverse()

		Y0 = 0.
		X0 = 0.

		for idx in range(len(x)):
			sigmasq = y[0]**2. / y[idx]
			Y0 += numpy.log(1. * y[idx] / y[0]) / sigmasq
			X0 += (x[idx]**2. - x[0]**2.) / sigmasq

		B = Y0 / X0
		A = y[0] * numpy.exp(-B * x[0]**2.)
		return (len(x), (A, B))

	elif rank_by == "uncombined-ifar":
		A = float(len(x)) * x[0] / t
		return (len(x), (A, 0))

def extrapolate_reputation(rank_by, coeffs, reputation, t):
	#
	# calculate the FAN from the reputation and the extrapolation coefficients
	#

	if rank_by == "snr":
		return coeffs[0] * numpy.exp(coeffs[1] * reputation**2.)
	if rank_by == "uncombined-ifar":
		return coeffs[0] * t / reputation


#
# =============================================================================
#
#                                 Book-Keeping
#
# =============================================================================
#


class Summaries(object):
#	def __init__(self, category_algorithm, rank_by, mass_bins = None):
#		if category_algorithm == "mchirp-ifos-oninstruments":
#			self.category_func = lambda self, on_instruments, participating_instruments, mchirp, mtotal: (on_instruments, participating_instruments, self.mass_bins[mchirp])
#		elif category_algorithm == "mtotal-ifos-oninstruments":
#			self.category_func = lambda self, on_instruments, participating_instruments, mchirp, mtotal: (on_instruments, participating_instruments, self.mass_bins[mtotal])
#		elif category_algorithm == "oninstruments":
#			self.category_func = lambda self, on_instruments, participating_instruments, mchirp, mtotal: on_instruments
#		else:
#			raise ValueError, category_algorithm
#		self.category_func = instancemethod(self.category_func, self, self.__class__)
	def __init__(self, category_algorithm, rank_by, frequency_bins = None):
		if category_algorithm == "frequency-ifos-oninstruments":
                        self.category_func = lambda self, on_instruments, participating_instruments, frequency: (on_instruments, participating_instruments, self.frequency_bins[frequency])
		elif category_algorithm == "oninstruments":
			self.category_func = lambda self, on_instruments, participating_instruments, frequency: on_instruments
		else:
			raise ValueError, category_algorithm
		self.category_func = instancemethod(self.category_func, self, self.__class__)

		if rank_by == "snr":
			self.reputation_func = lambda self, snr, uncombined_ifar, likelihood: snr
		elif rank_by == "uncombined-ifar":
			# cast to float so this does the right thing when
			# we get "inf" as a string
			self.reputation_func = lambda self, snr, uncombined_ifar, likelihood: float(uncombined_ifar)
		elif rank_by == "likelihood":
			self.reputation_func = lambda self, snr, uncombined_ifar, likelihood: likelihood
		else:
			raise ValueError, rank_by
		self.rank_by = rank_by
		self.reputation_func = instancemethod(self.reputation_func, self, self.__class__)

#		self.mass_bins = mass_bins
		self.frequency_bins = frequency_bins
		self.reputations = {}
		self.cached_livetime = {}
		self.extrapolate = False
		self.extrapolation_coeffs = {}
		self.categories = []

	def add_livetime(self, connection, live_time_program, veto_segments_name = None, verbose = False):
		if veto_segments_name is not None:
			if verbose:
				print >>sys.stderr, "\tretrieving veto segments \"%s\" ..." % veto_segments_name
			veto_segments = db_thinca_rings.get_veto_segments(connection, veto_segments_name)
		else:
			veto_segments = segments.segmentlistdict()
		if verbose:
			print >>sys.stderr, "\tcomputing livetimes:",
# does db_thinca_rings exist for rinca, or is it unnecessary as rinca does not have rings?
		bglivetime = 0
		xmldoc = dbtables.get_xml(connection)
		segs = llwapp.segmentlistdict_fromsearchsummary(xmldoc,program="lalapps_ring")
		segs = table.get_table(xmldoc, "search_summary").get_out_segmentlistdict()
		fglivetime = float(abs(segs.intersection(segs.keys())))
		for val in table.get_table(xmldoc, "time_slide").as_dict().values():
			#print k, val
			#for offset_vector in table.get_table(xmldoc, "time_slide").get_offset_dict(k):
			segs.offsets.update(val)
			bglivetime += float(abs(segs.intersection(val.keys())))
		if verbose: print >>sys.stderr, "\n\tforeground livetime %f, background livetime %f\n" % (fglivetime, bglivetime)
		bglivetime -= fglivetime
		on_instruments = lsctables.ifos_from_instrument_set(segs.keys())
		try:
			self.cached_livetime[on_instruments] += bglivetime
		except KeyError:
			self.cached_livetime[on_instruments] = bglivetime
			
		#for on_instruments, livetimes in db_thinca_rings.get_thinca_livetimes(db_thinca_rings.get_thinca_rings_by_available_instruments(connection, program_name = live_time_program), veto_segments, db_thinca_rings.get_background_offset_vectors(connection), verbose = verbose).items():
		#	on_instruments = lsctables.ifos_from_instrument_set(on_instruments)
		#	try:
		#		self.cached_livetime[on_instruments] += sum(livetimes)
		#	except KeyError:
		#		self.cached_livetime[on_instruments] = sum(livetimes)
		#if verbose:
		#	print >>sys.stderr

#	def add_coinc(self, on_instruments, participating_instruments, mchirp, mtotal, snr, uncombined_ifar, likelihood):
#		self.reputations.setdefault(self.category_func(on_instruments, participating_instruments, mchirp, mtotal), []).append(self.reputation_func(snr, uncombined_ifar, likelihood))
#		if self.category_func(on_instruments, participating_instruments, mchirp, mtotal) not in self.categories:
#			self.categories.append(self.category_func(on_instruments, participating_instruments, mchirp, mtotal))
	def add_coinc(self, on_instruments, participating_instruments, frequency, snr, uncombined_ifar, likelihood):
		self.reputations.setdefault(self.category_func(on_instruments, participating_instruments, frequency), []).append(self.reputation_func(snr, uncombined_ifar, likelihood))
		if self.category_func(on_instruments, participating_instruments, frequency) not in self.categories:
			self.categories.append(self.category_func(on_instruments, participating_instruments, frequency))

	def index(self):
		for reputations in self.reputations.values():
			reputations.sort()

	def rate_extrapolation(self, N):
		#
		# calculate the FAR extrapolation coefficients for the different categories
		#

		self.extrapolate = True
		for category in self.categories:
			t = self.cached_livetime.setdefault(category, 0.0)
			reputations = self.reputations.setdefault(category, [])
			self.extrapolation_coeffs[category] = extrapolation_coeffs(self.rank_by, N, reputations, t)

	def rate(self, on_instruments, participating_instruments, frequency, snr, uncombined_ifar, likelihood):
		#
		# retrieve the appropriate reputation list (create an empty
		# one if there are no reputations for this category)
		#

		category = self.category_func(on_instruments, participating_instruments, frequency)
		reputations = self.reputations.setdefault(category, [])


		#
		# len(x) - bisect.bisect_left(x, reputation) = number of
		# elements in list >= reputation
		#

		n = len(reputations) - bisect.bisect_left(reputations, self.reputation_func(snr, uncombined_ifar, likelihood))

		#
		# retrieve the livetime
		#

		t = self.cached_livetime.setdefault(on_instruments, 0.0)
		if self.extrapolate:
			if n < self.extrapolation_coeffs[category][0]:
				n = extrapolate_reputation(self.rank_by, self.extrapolation_coeffs[category][1], self.reputation_func(snr, uncombined_ifar, likelihood), t)

		#
		# return the rate of events above the given reputation
		#
		try:
			return n / t
			
		except ZeroDivisionError, e:
			print >>sys.stderr, "found an event in category %s that has a livetime of 0 s" % repr(self.category_func(on_instruments, participating_instruments, frequency))
			raise e


#
# =============================================================================
#
#                                     Main
#
# =============================================================================
#


#
# command line
#


options, filenames = parse_command_line()


#
# initialize book-keeping
#


#background = Summaries(options.categories, options.rank_by, mass_bins = options.mass_bins)
background = Summaries(options.categories, options.rank_by, frequency_bins = options.frequency_bins)


#
# iterate over database files accumulating background statistics
#


if options.verbose:
	print >>sys.stderr, "collecting background statistics ..."


for n, filename in enumerate(filenames):
	#
	# open the database
	#

	if options.verbose:
		print >>sys.stderr, "%d/%d: %s" % (n + 1, len(filenames), filename)
	working_filename = dbtables.get_connection_filename(filename, tmp_path = options.tmp_space, verbose = options.verbose)
	connection = sqlite3.connect(working_filename)

	#
	# if the database contains a sim_inspiral table then it is assumed
	# to represent an injection run.  its rings must not added to the
	# livetime, and it cannot provide background coincs, so it is just
	# skipped altogether in this first pass.
	#

#	if "sim_inspiral" in dbtables.get_table_names(connection):
#		if options.verbose:
#			print >>sys.stderr, "\tdatabase contains sim_inspiral table, skipping ..."
	if "sim_ringdown" in dbtables.get_table_names(connection):
		if options.verbose:
			print >>sys.stderr, "\tdatabase contains sim_ringdown table, skipping ..."

		#
		# close the database
		#

		connection.close()
		dbtables.discard_connection_filename(filename, working_filename, verbose = options.verbose)
		continue

	#
	# compute and record background livetime
	#

	background.add_livetime(connection, options.live_time_program, veto_segments_name = options.veto_segments_name, verbose = options.verbose)

	#
	# count background coincs
	#

#	if options.verbose:
#		print >>sys.stderr, "\tcollecting background statistics ..."
#	for on_instruments, participating_instruments, mchirp, mtotal, snr, uncombined_ifar, likelihood in connection.cursor().execute("""
#SELECT
#	coinc_event.instruments,
#	coinc_inspiral.ifos,
#	coinc_inspiral.mchirp,
#	coinc_inspiral.mass,
#	coinc_inspiral.snr,
#	CASE coinc_inspiral.false_alarm_rate WHEN 0 THEN "inf" ELSE 1.0 / coinc_inspiral.false_alarm_rate END,
#	coinc_event.likelihood
#FROM
#	coinc_event
#	JOIN coinc_inspiral ON (
#		coinc_inspiral.coinc_event_id == coinc_event.coinc_event_id
#	)
#WHERE
#	-- require coinc to be background (= at least one of its time slide offsets is non-zero)
#	EXISTS (
#		SELECT
#			*
#		FROM
#			time_slide
#		WHERE
#			time_slide.time_slide_id == coinc_event.time_slide_id
#			AND time_slide.offset != 0
#	)
#	"""):
#		background.add_coinc(on_instruments, participating_instruments, mchirp, mtotal, snr, uncombined_ifar, likelihood)

	if options.verbose:
		print >>sys.stderr, "\tcollecting background statistics ..."
	for on_instruments, participating_instruments, frequency, snr, uncombined_ifar, likelihood in connection.cursor().execute("""
SELECT
	coinc_event.instruments,
	coinc_ringdown.ifos,
	coinc_ringdown.frequency,
	coinc_ringdown.snr,
	CASE coinc_ringdown.false_alarm_rate WHEN 0 THEN "inf" ELSE 1.0 / coinc_ringdown.false_alarm_rate END,
	coinc_event.likelihood
FROM
	coinc_event
	JOIN coinc_ringdown ON (
		coinc_ringdown.coinc_event_id == coinc_event.coinc_event_id
	)
WHERE
	-- require coinc to be background (= at least one of its time slide offsets is non-zero)
	EXISTS (
		SELECT
			*
		FROM
			time_slide
		WHERE
			time_slide.time_slide_id == coinc_event.time_slide_id
		AND time_slide.offset != 0
	)
	"""):
		background.add_coinc(on_instruments, participating_instruments, frequency, snr, uncombined_ifar, likelihood)

	#
	# close the database
	#

	connection.close()
	dbtables.discard_connection_filename(filename, working_filename, verbose = options.verbose)


background.index()
if options.extrapolation_num:
	if options.verbose:
		print >>sys.stderr, "\tcalculating FAR extrapolation coefficients ..."
	background.rate_extrapolation(options.extrapolation_num)

#
# iterate over database files assigning false-alarm rates to coincs
#


for n, filename in enumerate(filenames):
	#
	# open the database
	#

	if options.verbose:
		print >>sys.stderr, "%d/%d: %s" % (n + 1, len(filenames), filename)
	working_filename = dbtables.get_connection_filename(filename, tmp_path = options.tmp_space, verbose = options.verbose)
	connection = sqlite3.connect(working_filename)

	#
	# prepare the database
	#

	connection.create_function("background_rate", 6, background.rate)

	#
	# count background coincs by type and mass bin
	#

#	if options.verbose:
#		print >>sys.stderr, "\tcalculating and recording false alarm rates ..."
#	connection.cursor().execute("""
#UPDATE
#	coinc_inspiral
#SET
#	%s = (
#		SELECT
#			background_rate(
#				coinc_event.instruments,
#				coinc_inspiral.ifos,
#				coinc_inspiral.mchirp,
#				coinc_inspiral.mass,
#				coinc_inspiral.snr,
#				CASE coinc_inspiral.false_alarm_rate WHEN 0 THEN "inf" ELSE 1.0 / coinc_inspiral.false_alarm_rate END,
#				coinc_event.likelihood
#			)
#		FROM
#			coinc_event
#		WHERE
#			coinc_event.coinc_event_id == coinc_inspiral.coinc_event_id
#	)
#	""" % options.populate_column)
#	connection.commit()

	if options.verbose:
		print >>sys.stderr, "\tcalculating and recording false alarm rates ..."
	connection.cursor().execute("""
UPDATE
	coinc_ringdown
SET
	%s = (
		SELECT
			background_rate(
				coinc_event.instruments,
				coinc_ringdown.ifos,
				coinc_ringdown.frequency,
				coinc_ringdown.snr,
				CASE coinc_ringdown.false_alarm_rate WHEN 0 THEN "inf" ELSE 1.0 / coinc_ringdown.false_alarm_rate END,
				coinc_event.likelihood
			)
		FROM
			coinc_event
		WHERE
			coinc_event.coinc_event_id == coinc_ringdown.coinc_event_id
	)
	""" % options.populate_column)
	connection.commit()

#
	# close the database
	#

	connection.close()
	dbtables.put_connection_filename(filename, working_filename, verbose = options.verbose)
