universe = scheduler
executable = $ENV(LSC_DATAFIND_PATH)/LSCdataFind
arguments = --observatory $(observatory) --url-type file --gps-start-time $(gpsstarttime) --gps-end-time $(gpsendtime) --lal-cache --type $(inputdatatype) --match localhost/frames
getenv = True
log = $ENV(CONDOR_SUBLOGFILES_PATH)/datafind_$(tagstring).log
error = logs/datafind_$(tagstring).err
output = cache/$(macroobservatory)-$(macrogpsstarttime)-$(macrogpsendtime).cache
notification = never
queue 1
