universe = standard
executable = executables/lalapps_coire
arguments = --injection-file $(macroinjectionfile) --missed-injections $(macromissedinjections) --cluster-time 4000 --glob $(macroglob) --user-tag $(macrousertag) --summary $(macrosummary) --injection-window 50 --data-type all_data --coinc-stat effective_snrsq --output $(macrooutput)
environment = KMP_LIBRARY=serial;MKL_SERIAL=yes
log = /people/jclayton/logs/RmpMoimny
error = logs/coire-$(macroifo)-$(cluster)-$(process).err
output = logs/coire-$(macroifo)-$(cluster)-$(process).out
notification = never
queue 1
