universe = standard
executable = executables/lalapps_tmpltbank
arguments = --grid-spacing Hexagonal --dynamic-range-exponent 69.0 --enable-high-pass 30.0 --high-pass-order 8 --strain-high-pass-order 8 --maximum-mass 35.0 --approximant TaylorF2 --gps-end-time $(macrogpsendtime) --standard-candle --calibrated-data real_8 --candle-mass1 1 --candle-mass2 1 --channel-name $(macrochannelname) --space Tau0Tau3 --number-of-segments 15 --minimal-match 0.97 --candle-snr 8 --gps-start-time $(macrogpsstarttime) --high-pass-attenuation 0.1 --min-high-freq-cutoff SchwarzISCO --segment-length 1048576 --low-frequency-cutoff 40.0 --pad-data 8 --num-freq-cutoffs 1 --sample-rate 4096 --high-frequency-cutoff 2048.0 --resample-filter ldas --strain-high-pass-atten 0.1 --strain-high-pass-freq 30 --max-total-mass 35.0 --frame-cache $(macroframecache) --max-high-freq-cutoff SchwarzISCO --user-tag INJ001 --write-compress --minimum-mass 1.0 --order twoPN --spectrum-type median
environment = KMP_LIBRARY=serial;MKL_SERIAL=yes
log = /people/jclayton/logs/RmpMoimny
error = logs/tmpltbank-$(macrogpsstarttime)-$(macrogpsendtime)-$(cluster)-$(process).err
output = logs/tmpltbank-$(macrogpsstarttime)-$(macrogpsendtime)-$(cluster)-$(process).out
notification = never
queue 1
