.TH LAL 3 "LSC Algorithm Library" "LSC"
.SH NAME
LAL - LSC Algorithm Library
.SH SYNOPSIS
#include <lal/...>
.SH DESCRIPTION
The LSC Algorithm Library (LAL) is a collection of routines for gravitational
wave data analysis.
.PP
For more information please consult the LAL Scientific Documentation manual,
which is installed with the LAL library.  For more information, consult
the LAL webpage
.B http://www.lsc-group.phys.uwm.edu/lal
